"""initial migration

Revision ID: 1b6da3a88183
Revises:
Create Date: 2026-04-10 16:56:25.653637

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1b6da3a88183'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'state',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('code', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('uf', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('base_cost_per_kwl', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_state_code'), 'state', ['code'], unique=True)
    op.create_index(op.f('ix_state_uf'), 'state', ['uf'], unique=False)
    op.create_table(
        'supplier',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('code', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('banner', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('kwl_cost', sa.Integer(), nullable=False),
        sa.Column('total_clients', sa.Integer(), nullable=False),
        sa.Column('avg_rating', sa.Float(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_supplier_code'), 'supplier', ['code'], unique=True)
    op.create_index(op.f('ix_supplier_nome'), 'supplier', ['nome'], unique=False)
    op.create_table(
        'supplier_state',
        sa.Column('supplier_id', sa.Integer(), nullable=False),
        sa.Column('state_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['state_id'],
            ['state.id'],
        ),
        sa.ForeignKeyConstraint(
            ['supplier_id'],
            ['supplier.id'],
        ),
        sa.PrimaryKeyConstraint('supplier_id', 'state_id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supplier_state')
    op.drop_index(op.f('ix_supplier_nome'), table_name='supplier')
    op.drop_index(op.f('ix_supplier_code'), table_name='supplier')
    op.drop_table('supplier')
    op.drop_index(op.f('ix_state_uf'), table_name='state')
    op.drop_index(op.f('ix_state_code'), table_name='state')
    op.drop_table('state')
    # ### end Alembic commands ###
