"""change column name in Supplier

Revision ID: a47c3948ac8f
Revises: 1b6da3a88183
Create Date: 2026-04-10 18:08:21.832572

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a47c3948ac8f'
down_revision: Union[str, Sequence[str], None] = '1b6da3a88183'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplier', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_index(op.f('ix_supplier_nome'), table_name='supplier')
    op.create_index(op.f('ix_supplier_name'), 'supplier', ['name'], unique=False)
    op.drop_column('supplier', 'nome')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplier', sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_supplier_name'), table_name='supplier')
    op.create_index(op.f('ix_supplier_nome'), 'supplier', ['nome'], unique=False)
    op.drop_column('supplier', 'name')
    # ### end Alembic commands ###
